# Valentine's Day Bot

service: valentines-day-bot
frameworkVersion: ">=1.6.0 <2.0.0"

provider:
  name: azure
  location: East US

plugins:
  - serverless-azure-functions

# you can define service wide environment variables here
environment:
  TWIT_API_KEY: ${file(./env.json):TWIT_API_KEY}
  TWIT_API_KEY_SECRET: ${file(./env.json):TWIT_API_KEY_SECRET}
  TWIT_ACCESS_TOKEN: ${file(./env.json):TWIT_ACCESS_TOKEN}
  TWIT_ACCESS_TOKEN_SECRET: ${file(./env.json):TWIT_ACCESS_TOKEN_SECRET}
  TWIT_TIMEOUT_MS: ${file(./env.json):TWIT_TIMEOUT_MS}
  TWIT_HASHTAG: ${file(./env.json):TWIT_HASHTAG}
  BUCKET: ${file(./env.json):BUCKET}

functions:
  handleMentions:
    handler: handleMentions.replyToTweets
    events:
      - timer:
        x-azure-settings:
          name: timerObj
          schedule: 0 */1 * * * *
