# Valentine's Day Bot

service: valentines-day-bot

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs4.3

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"

# you can define service wide environment variables here
  environment:
    TWIT_API_KEY: ${file(./env.json):TWIT_API_KEY}
    TWIT_API_KEY_SECRET: ${file(./env.json):TWIT_API_KEY_SECRET}
    TWIT_ACCESS_TOKEN: ${file(./env.json):TWIT_ACCESS_TOKEN}
    TWIT_ACCESS_TOKEN_SECRET: ${file(./env.json):TWIT_ACCESS_TOKEN_SECRET}
    TWIT_TIMEOUT_MS: ${file(./env.json):TWIT_TIMEOUT_MS}
    TWIT_HASHTAG: ${file(./env.json):TWIT_HASHTAG}
    S3_BUCKET: ${file(./env.json):S3_BUCKET}

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  handleMentions:
    handler: handlers/replyToTweets.replyToTweets
    description: Scans mentions and responds # description to publish to AWS
    memorySize: 1024 # default is 1024
    timeout: 15 # default is 6
    events:
      - schedule: rate(3 minutes)

  reply:
    handler: handlers/reply.reply
    description: Replies to tweets # description to publish to AWS
    memorySize: 1024 # default is 1024
    timeout: 15 # default is 6
    events:
      - sns: twitter-mention
      - displayName: Twitter mention from Streaming API

#    Define function environment variables here
#    environment:
#      variable2: value2
