# Valentine's Day Bot

service: valentines-day-bot
frameworkVersion: ">=1.6.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  memorySize: 512 

# you can define service wide environment variables here
  environment:
    TWIT_API_KEY: ${file(./env.json):TWIT_API_KEY}
    TWIT_API_KEY_SECRET: ${file(./env.json):TWIT_API_KEY_SECRET}
    TWIT_ACCESS_TOKEN: ${file(./env.json):TWIT_ACCESS_TOKEN}
    TWIT_ACCESS_TOKEN_SECRET: ${file(./env.json):TWIT_ACCESS_TOKEN_SECRET}
    TWIT_TIMEOUT_MS: ${file(./env.json):TWIT_TIMEOUT_MS}
    TWIT_HASHTAG: ${file(./env.json):TWIT_HASHTAG}
    S3_BUCKET: ${file(./env.json):S3_BUCKET}

functions:
  handleMentions:
    handler: handlers/replyToTweets.replyToTweets
    description: Scans mentions and responds # description to publish to AWS
    memorySize: 1024 # default is 1024
    timeout: 15 # default is 6
    events:
      - schedule: rate(2 minutes)

  reply:
    handler: handlers/reply.reply
    description: Replies to tweets # description to publish to AWS
    memorySize: 1024 # default is 1024
    timeout: 15 # default is 6
    events:
      - sns: twitter-mention
      - displayName: Twitter mention from Streaming API
